[package]
name = "blahaj"
version = "0.2.0"
license = "MIT"
authors = ["Isabel Roses <isabel@isabelroses.com>"]
description = "the resident discord bot of :3"
readme = "README.md"
homepage = "https://github.com/isabelroses/blahaj"
repository = "https://github.com/isabelroses/blahaj"
keywords = ["discord", "bot", "serenity"]
edition = "2021"
rust-version = "1.78.0"

[dependencies]
bottomify = "1.2.0"
color-eyre = "0.6.3"
dotenv = "0.15.0"
humantime = "2.1.0"
kittysay = "0.8.0"
poise = "0.6.1"
rand = "0.8.5"
regex = "1.10.5"
serenity = "0.12.2"

[dependencies.serde]
version = "1.0.203"
features = ["derive"]

[dependencies.reqwest ]
version = "0.12.4"
features = ["json"]

[dependencies.tokio]
version = "1.38.0"
features = ["macros", "rt-multi-thread"]

[dependencies.git-tracker]
git = "https://github.com/getchoo/nixpkgs-tracker-bot"

[lints.clippy]
all = "warn"
pedantic = "warn"
